---
- name: Converge
  hosts: all
  roles:
    - role: ansible-bitwarden-lookup-plugin
  tasks:
    - name: generate test file
      template:
        src: testfile.txt.j2
        dest: /testfile.txt
